GET http://localhost:5150/user

###
GET http://localhost:5150/user/1

###

POST http://localhost:5150/user
Content-Type: application/json

{
  "username": "Mara",
  "email": "mara@example.com"
}

###
PUT http://localhost:5150/user/1
Content-Type: application/json

{
  "username": "JaneDoe",
  "email": "jane.doe@example.com"
}

###
DELETE http://localhost:5150/user/1